# Generated by Django 5.2.13 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], default='telegram', max_length=16)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('moderation_mode', models.CharField(choices=[('balanced', 'Balanced'), ('strict', 'Strict'), ('paranoid', 'Paranoid')], default='balanced', max_length=16)),
                ('bot_status', models.CharField(choices=[('online', 'Online'), ('paused', 'Paused'), ('offline', 'Offline')], default='online', max_length=16)),
                ('whitelist_guard_enabled', models.BooleanField(default=True)),
                ('vector_fallback_enabled', models.BooleanField(default=True)),
                ('messages_scanned', models.PositiveBigIntegerField(default=0)),
                ('blocked_messages', models.PositiveBigIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
