# Generated by Django 6.0.4 on 2026-04-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=120)),
                ('telegram_first_name', models.CharField(blank=True, max_length=120)),
                ('matched_word', models.CharField(blank=True, max_length=200)),
                ('decision_reason', models.CharField(blank=True, max_length=100)),
                ('message_text', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='channels_app.managedchannel')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='OffenderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=120)),
                ('telegram_first_name', models.CharField(blank=True, max_length=120)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('top_word', models.CharField(blank=True, max_length=200)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender_stats', to='channels_app.managedchannel')),
            ],
            options={
                'ordering': ('-violation_count',),
                'unique_together': {('channel', 'telegram_user_id')},
            },
        ),
    ]
